root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./main.go"
entrypoint = ["./tmp/main"]
include_ext = ["go"]
exclude_dir = ["database", "tmp", "vendor", "node_modules"]
delay = 1000  # ms

[log]
time = true

[misc]
clean_on_exit = true
