services:
  db:
    container_name: workoutDB
    image: postgres:18-alpine
    ports:
    - "${DB_PORT}:5432"
    env_file:
     - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database/pgdata:/var/lib/postgresql:rw
    restart: unless-stopped
